### ISSUE TITLE
Delete after search

### ISSUE THREAD

**Issue by balrok** [junegunn/vim-slash#12]
Not sure if this is a bug or intended. After searching I can not delete anything.
E.g.
```
/test
dw
```
So pressing `d` after search has no effect. Other keys like `i`, `s` etc. are fine.

I'm not sure if this happened due to some interaction with my config or if it is even intented.
So if you want more detailed information I will start debugging.
Ps: I use vim8 and neovim 0.2

**Comment by junegunn** [comment]
It's definitely not intended, and I don't have the problem. You might want to remove all your other plugins and configurations and see if it's still reproducible, and gradually restore the settings until you run into the issue.

**Comment by balrok** [comment]
Maybe you want to debug this.. I couldn't reproduce it now with vim8 because I'm on another computer.

The issue happens here with neovim + neomake + vim-slash

This is my vimrc
```
source $HOME/.vim/plug.vim
```


and plug.vim
```
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-slash'
Plug 'neomake/neomake'
call plug#end()
```
Removing either will fix the issue
Using: https://github.com/pgdouyon/vim-evanesco will fix the issue also

**Comment by junegunn** [comment]
I don't use neomake so it's not my priority, but thanks for the information.
