### ISSUE TITLE
Only opens a single fold level

### ISSUE THREAD

**Issue by otommod** [junegunn/vim-slash#13]
`zo`, as the title says, only opens a single fold level.  So in a file with deeply nested folds, you still can't see the search.  

You could use `zo` with a count, but I think it's easier to use `zv`, which opens enough so that the cursor will be visible.  There's also `zO`.

**Comment by auwsmit** [comment]
You can workaround this by adding `noremap <Plug>(slash-after) zv` to your vimrc

**Comment by junegunn** [comment]
Thanks, I changed `zo` to `zv` as you suggested.

**Comment by otommod** [comment]
@AssailantLF Given that this is the way works by default (see 'foldopen'), I think it makes sense to follow that behavior.
@junegunn thank you for all the other plugins and projects you've written as well!

**Comment by auwsmit** [comment]
Oh yeah, I think it makes more sense too, I was just providing a workaround (that I was using) until a fix was made.
