### ISSUE TITLE
Conflict with mappings.

### ISSUE THREAD

**Issue by Gomme-** [junegunn/vim-slash#15]
Hello,

I have the following mapping in my vimrc (among others, basically I exchange keys around as I use a french bépo keyboard)
noremap n l
noremap k n
noremap N L
noremap K N

And I can't figure out how to make the plugin to work with these. Any ideas?

**Comment by rawaludin** [comment]
To override it, you can put your mapping in `~/.vim/after/plugin` and read `:h after-directory`

**Comment by Gomme-** [comment]
> To override it, you can put your mapping in `~/.vim/after/plugin` and read `:h after-directory`

It works. Thank you very much. I didn’t know about the "after-directory" functionality.
