### ISSUE TITLE
Blink doesn’t work in NeoVim

### ISSUE THREAD

**Issue by lunacookies** [junegunn/vim-slash#17]
Hi, I just wanted to say that, using the blink snippet provided in the README, a yellow block appears around the cursor when jumping from match to match in NeoVim v0.3.1, but it doesn’t blink (unlike [default Vim 8.0 from macOS Mojave with the same vimrc as NeoVim], which works flawlessly and _does_ blink).

I think this means that NeoVim thinks it has timers, but that they somehow don’t execute (?)

**Comment by junegunn** [comment]
I can confirm. Probably related: https://github.com/neovim/neovim/issues/6829

**Comment by lunacookies** [comment]
Interesting, thanks for the info …
