### ISSUE TITLE
wrap error

### ISSUE THREAD

**Issue by ErrEoE** [junegunn/vim-slash#18]
when i have a map 
`nmap <leader>gb :Grepper -tool rg -buffer -cword<cr>`, I input `<leader>gb`, the vim ouput error:

```
E117: Unknown function: <SNR>68_wrap
E15: Invalida expression: <80><fd>R68_wrap("\^M")
```

**Comment by junegunn** [comment]
Use `nnoremap` instead and see if it helps.

**Comment by ErrEoE** [comment]
This is still occur. I input `Enter` in the command, it also can cause similar error.

**Comment by thomasjachmann** [comment]
I also have this problem when using vim-slash and vim-grepper. After using my grepper mapping, no command works anymore. I cannot even quit neovim normally, I then need to `kill` it.

My mapping:
```
map <Leader>f :Grepper -tool rg -highlight -grepprg rg -H --no-heading --vimgrep --hidden --sort-files --smart-case<CR>
```

This also hpapens with `nnoremap`. When I deactivate vim-slash, everything works fine.

**Comment by ErrEoE** [comment]
I comment `cnoremap <expr> <cr> <sid>slashwrap("\<cr>")`, everything works fine.

**Comment by mhinz** [comment]
I only learned about this issue today. It should be fixed now.

**Comment by thomasjachmann** [comment]
I can confirm. At least, it's fixed for my setup. Thanks!
