### ISSUE TITLE
A plugin that is incompatible with vim-slash

### ISSUE THREAD

**Issue by rafaeln** [junegunn/vim-slash#2]
Hi. Great plugin. I was using [vim-visual-star-search](https://github.com/bronson/vim-visual-star-search) before, which is for doing part of what vim-slash does, namely, allowing `*` and `#` in visual mode. The plugins are incompatible, as expected, with vim-visual-star-search overriding vim-slash immobile `*` and `#` remaps. I thought I could tell you, in case you thought useful to one day register that in your readme.

**Comment by junegunn** [comment]
Thanks for sharing.
