### ISSUE TITLE
error jump when execute on a unique word

### ISSUE THREAD

**Issue by SolaWing** [junegunn/vim-slash#21]

**Comment by demon386** [comment]
I encountered a similar problem so I want to provide more descriptions here.

When there's only one match for the current word, when pressing "*" on this word, it will actually execute "``" to jump to the last position in jumplist, which is a strange behavior.

**Comment by junegunn** [comment]
~~Before 07394361aa045d2d8d3d461ae297d95a949a67f9 or after it?~~

07394361aa045d2d8d3d461ae297d95a949a67f9 may have caused it.

**Comment by demon386** [comment]
After. I use neovim head version.

**Comment by demon386** [comment]
After. I use neovim head version.

**Comment by junegunn** [comment]
Let me know if the patch doesn't help.

**Comment by demon386** [comment]
@junegunn Works well. Thanks!
