### ISSUE TITLE
Shortmess counter

### ISSUE THREAD

**Issue by crivotz** [junegunn/vim-slash#25]
Hi, I have just noticed that using **vim-slash** I find myself no longer having the counter of the elements found (provided by the shortmess S)

I've seen that there was a similar closed issue #7 but in this case the option for counter became native.

Thanks

**Comment by garymh** [comment]
Hi - count me in for wanting this too 😄

**Comment by crivotz** [comment]
> Hi - count me in for wanting this too

At the moment I have changed plugin, but I still leave open the issue 😄

**Comment by junegunn** [comment]
Hmm, I don't know how to fix this. vim-slash needs to perform some additional action after the basic search operations (`n`, `/`, ...), but when we do it, Vim refuses to print the counter.

```vim
" Prints counter
nnoremap <leader>n n

" Let's move the cursor to the right after n.
" Does not print counter
nnoremap <leader>n nl
```

Same holds true for `feedkeys`:

```vim
" Prints counter
call feedkeys('n', 'n')

" Does not print counter
call feedkeys('nl', 'n')

" Doesn't print either
call feedkeys('n', 'n') | call feedkeys('l', 'n')
``

**Comment by garymh** [comment]
🤔 That stinks. Is that a bug with vim? Trying it manually (in neovim, though) drops the the index/total but keeps the index. For example:

Statusline: `--VISUAL--         [1/7]`
[press n] 
Statusline: `--VISUAL--         [2/7]`
[press l]
Statusline: `--VISUAL--         2`

**Comment by crivotz** [comment]
I think the issue is due to the fact that the second command cleans up the part where the counter message should appear.

If I try in vim to launch the command `call feedkeys('nl', 'n')` I see appear a quick blink `l`
If I try to launch the following `call feedkeys('nl', 'n') | echo searchcount().current` I see that the counter is always updated correctly.

`searchcount()` work under vim, I don't know the right command for neovim
