### ISSUE TITLE
customizable mappings

### ISSUE THREAD

**Issue by alok** [junegunn/vim-slash#3]
This plugin takes over the `n` and `N` mappings, making it difficult to combine it with plugins like `indexed-search`. Could you make the mapping disable if mappings already exist for `/`,`?`,`n`,`N`, `*`, `#`?

**Comment by junegunn** [comment]
Hi, vim-slash is more like a subset of my personal Vim configuration so I'm not interested in adding anything that I don't need. But feel free to fork and change it to your needs.
