### ISSUE TITLE
Plugin inserts text <Plug>(slash-trailer)

### ISSUE THREAD

**Issue by rafaeln** [junegunn/vim-slash#4]
(The cursor is the `|`)

If I have the following text in a buffer:

```text
| a sentence and the end
```

And I do `c/and<cr>`, what I get is

```text
<Plug>(slash-trailer)|and the end
```

**Comment by junegunn** [comment]
Fixed it, thanks for the report. Let me know if you still see issues.

**Comment by rafaeln** [comment]
Thanks for the prompt fix! Now it works perfectly.
